version: '3'
services:
  backend-factory:
    build:
      context: .
      dockerfile: ./Dockerfile.back
      args:
        WORKDIR: factory
        PORT: 8083
    ports:
      - "8083:8083"
    networks:
      - shared-network

  backend-shop:
    build:
      context: .
      dockerfile: ./Dockerfile.back
      args:
        WORKDIR: shop
        PORT: 8082
    ports:
      - "8082:8082"
    networks:
      - shared-network

  backend-gateway:
    build:
      context: .
      dockerfile: ./Dockerfile.back2
      args:
        WORKDIR: gateway
        PORT: 8081
    environment:
      SHOP_ENDPOINT: $SHOP_ENDPOINT
      FACTORY_ENDPOINT: $FACTORY_ENDPOINT
    ports:
      - "8081:8081"
    networks:
      - shared-network

  react-front:
    build:
      context: .
      dockerfile: ./Dockerfile.front
    ports:
      - "3000:3000"
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
    external: true
