# version: '3'
# services:
#   backend-factory:
#     build: 
#       context: .
#       dockerfile: ./Dockerfile.back
#       args:
#         WORKDIR: factory
#         PORT: 8083
#     ports:
#       - "8083:8083"
#     networks:
#       - shared-network
#   backend-shop:
#     build: 
#       context: .
#       dockerfile: ./Dockerfile.back
#       args:
#         WORKDIR: shop
#         PORT: 8082
#     ports:
#       - "8082:8082"
#   react-front:
#     build:
#       context: .
#       dockerfile: ./Dockerfile.front
#     ports:
#       - "3000:3000"
# networks:
#   shared-network:
#     external: true

version: '3'
services:
  backend-factory:
    build: 
      context: .
      dockerfile: ./Dockerfile.back
      args:
        WORKDIR: factory
        PORT: 8083
    ports:
      - "8083:8083"
    networks:
      - shared-network

  backend-shop:
    build: 
      context: .
      dockerfile: ./Dockerfile.back
      args:
        WORKDIR: shop
        PORT: 8082
    ports:
      - "8082:8082"
    networks:
      - shared-network

  react-front:
    build:
      context: .
      dockerfile: ./Dockerfile.front
    ports:
      - "3000:3000"

networks:
  shared-network:
    external: true

