version: '3'
services:
  backend-gateway:
    build: 
      context: .
      dockerfile: ./Dockerfile.back2
      args:
        WORKDIR: gateway
        PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - shared-network
networks:
  shared-network:
    external: true
